// <auto-generated />
using EasyTalentos.Repositorio.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyTalentos.Repositorio.Migrations
{
    [DbContext(typeof(EasyContext))]
    [Migration("20201116003053_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portfolio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PretencaoSalario")
                        .HasColumnType("float");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Rio Grande do Sul",
                            Email = "Lesojo@outlook.com",
                            Estado = "SP",
                            Linkedin = "http://linkedin.com",
                            Nome = "Buvimugae",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 4298.0,
                            Telefone = "(21) 95930-3353"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Alagoas",
                            Email = "SHylyjae@outlook.com",
                            Estado = "DF",
                            Linkedin = "http://linkedin.com",
                            Nome = "Kenaepizhae",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 1742.0,
                            Telefone = "(13) 94571-3712"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Bahia",
                            Email = "Naecaexae@hotmail.com",
                            Estado = "BA",
                            Linkedin = "http://linkedin.com",
                            Nome = "Jokeqasu",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 1561.0,
                            Telefone = "(11) 94561-9958"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Espírito Santo",
                            Email = "Seqyka@outlook.com",
                            Estado = "MT",
                            Linkedin = "http://linkedin.com",
                            Nome = "Qaetaridi",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 1269.0,
                            Telefone = "(36) 96113-7597"
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Pernambuco",
                            Email = "ZHamapae@outlook.com",
                            Estado = "AC",
                            Linkedin = "http://linkedin.com",
                            Nome = "Majibopae",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 3474.0,
                            Telefone = "(23) 99881-6426"
                        },
                        new
                        {
                            Id = 6,
                            Cidade = "Distrito Federal",
                            Email = "Haravy@hotmail.com",
                            Estado = "GO",
                            Linkedin = "http://linkedin.com",
                            Nome = "Girylaeha",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 3130.0,
                            Telefone = "(33) 95836-7560"
                        },
                        new
                        {
                            Id = 7,
                            Cidade = "Piauí",
                            Email = "Cygejy@outlook.com",
                            Estado = "BA",
                            Linkedin = "http://linkedin.com",
                            Nome = "Mymocula",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 4721.0,
                            Telefone = "(33) 94176-8341"
                        },
                        new
                        {
                            Id = 8,
                            Cidade = "Paraíba",
                            Email = "Lebuje@outlook.com",
                            Estado = "PA",
                            Linkedin = "http://linkedin.com",
                            Nome = "Qiveluwe",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 3820.0,
                            Telefone = "(31) 95924-3470"
                        },
                        new
                        {
                            Id = 9,
                            Cidade = "Espírito Santo",
                            Email = "Jaxuta@hotmail.com",
                            Estado = "RJ",
                            Linkedin = "http://linkedin.com",
                            Nome = "SHytiwylo",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 1211.0,
                            Telefone = "(14) 98138-9526"
                        },
                        new
                        {
                            Id = 10,
                            Cidade = "Pará",
                            Email = "Guvaeha@outlook.com",
                            Estado = "AM",
                            Linkedin = "http://linkedin.com",
                            Nome = "Vajigyxi",
                            Portfolio = "http://portfolio.com",
                            PretencaoSalario = 4107.0,
                            Telefone = "(38) 91289-2781"
                        });
                });

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Conhecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Android")
                        .HasColumnType("int");

                    b.Property<int>("Angular")
                        .HasColumnType("int");

                    b.Property<int>("AngularJs")
                        .HasColumnType("int");

                    b.Property<int>("AspNetMvc")
                        .HasColumnType("int");

                    b.Property<int>("AspNetWebForm")
                        .HasColumnType("int");

                    b.Property<int>("Bootstrap")
                        .HasColumnType("int");

                    b.Property<int>("C")
                        .HasColumnType("int");

                    b.Property<int>("CSharp")
                        .HasColumnType("int");

                    b.Property<int>("Cake")
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("Css")
                        .HasColumnType("int");

                    b.Property<int>("DJango")
                        .HasColumnType("int");

                    b.Property<int>("ExpressNodeJs")
                        .HasColumnType("int");

                    b.Property<int>("Flask")
                        .HasColumnType("int");

                    b.Property<int>("Flutter")
                        .HasColumnType("int");

                    b.Property<int>("Html")
                        .HasColumnType("int");

                    b.Property<int>("Illustrator")
                        .HasColumnType("int");

                    b.Property<int>("Ionic")
                        .HasColumnType("int");

                    b.Property<int>("Ios")
                        .HasColumnType("int");

                    b.Property<int>("Java")
                        .HasColumnType("int");

                    b.Property<int>("Jquery")
                        .HasColumnType("int");

                    b.Property<int>("Laravel")
                        .HasColumnType("int");

                    b.Property<string>("LinkCrud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Majento")
                        .HasColumnType("int");

                    b.Property<int>("MySql")
                        .HasColumnType("int");

                    b.Property<int>("MySqlServer")
                        .HasColumnType("int");

                    b.Property<int>("NodeJs")
                        .HasColumnType("int");

                    b.Property<string>("Outras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Photoshop")
                        .HasColumnType("int");

                    b.Property<int>("Php")
                        .HasColumnType("int");

                    b.Property<int>("Python")
                        .HasColumnType("int");

                    b.Property<int>("ReactJs")
                        .HasColumnType("int");

                    b.Property<int>("ReactNative")
                        .HasColumnType("int");

                    b.Property<int>("Ruby")
                        .HasColumnType("int");

                    b.Property<int>("SalesForce")
                        .HasColumnType("int");

                    b.Property<int>("Seo")
                        .HasColumnType("int");

                    b.Property<int>("Swift")
                        .HasColumnType("int");

                    b.Property<int>("Vue")
                        .HasColumnType("int");

                    b.Property<int>("WordPress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId")
                        .IsUnique();

                    b.ToTable("Conhecimento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Android = 1,
                            Angular = 3,
                            AngularJs = 2,
                            AspNetMvc = 4,
                            AspNetWebForm = 4,
                            Bootstrap = 3,
                            C = 4,
                            CSharp = 0,
                            Cake = 1,
                            CandidatoId = 1,
                            Css = 1,
                            DJango = 2,
                            ExpressNodeJs = 3,
                            Flask = 4,
                            Flutter = 1,
                            Html = 3,
                            Illustrator = 2,
                            Ionic = 2,
                            Ios = 2,
                            Java = 3,
                            Jquery = 4,
                            Laravel = 0,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 0,
                            MySql = 3,
                            MySqlServer = 4,
                            NodeJs = 4,
                            Outras = "(Outras linguagens)",
                            Photoshop = 2,
                            Php = 3,
                            Python = 4,
                            ReactJs = 3,
                            ReactNative = 1,
                            Ruby = 3,
                            SalesForce = 0,
                            Seo = 0,
                            Swift = 4,
                            Vue = 0,
                            WordPress = 3
                        },
                        new
                        {
                            Id = 2,
                            Android = 4,
                            Angular = 3,
                            AngularJs = 2,
                            AspNetMvc = 2,
                            AspNetWebForm = 4,
                            Bootstrap = 3,
                            C = 0,
                            CSharp = 3,
                            Cake = 1,
                            CandidatoId = 2,
                            Css = 2,
                            DJango = 3,
                            ExpressNodeJs = 1,
                            Flask = 1,
                            Flutter = 3,
                            Html = 1,
                            Illustrator = 4,
                            Ionic = 4,
                            Ios = 2,
                            Java = 1,
                            Jquery = 4,
                            Laravel = 0,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 4,
                            MySql = 1,
                            MySqlServer = 0,
                            NodeJs = 3,
                            Outras = "(Outras linguagens)",
                            Photoshop = 0,
                            Php = 3,
                            Python = 1,
                            ReactJs = 2,
                            ReactNative = 3,
                            Ruby = 4,
                            SalesForce = 2,
                            Seo = 0,
                            Swift = 3,
                            Vue = 0,
                            WordPress = 1
                        },
                        new
                        {
                            Id = 3,
                            Android = 1,
                            Angular = 1,
                            AngularJs = 3,
                            AspNetMvc = 1,
                            AspNetWebForm = 0,
                            Bootstrap = 3,
                            C = 4,
                            CSharp = 0,
                            Cake = 4,
                            CandidatoId = 3,
                            Css = 1,
                            DJango = 3,
                            ExpressNodeJs = 4,
                            Flask = 2,
                            Flutter = 4,
                            Html = 4,
                            Illustrator = 1,
                            Ionic = 3,
                            Ios = 3,
                            Java = 4,
                            Jquery = 3,
                            Laravel = 1,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 0,
                            MySql = 3,
                            MySqlServer = 2,
                            NodeJs = 1,
                            Outras = "(Outras linguagens)",
                            Photoshop = 2,
                            Php = 2,
                            Python = 2,
                            ReactJs = 3,
                            ReactNative = 1,
                            Ruby = 3,
                            SalesForce = 1,
                            Seo = 2,
                            Swift = 4,
                            Vue = 2,
                            WordPress = 2
                        },
                        new
                        {
                            Id = 4,
                            Android = 1,
                            Angular = 4,
                            AngularJs = 3,
                            AspNetMvc = 0,
                            AspNetWebForm = 2,
                            Bootstrap = 1,
                            C = 2,
                            CSharp = 1,
                            Cake = 1,
                            CandidatoId = 4,
                            Css = 2,
                            DJango = 4,
                            ExpressNodeJs = 1,
                            Flask = 2,
                            Flutter = 4,
                            Html = 4,
                            Illustrator = 1,
                            Ionic = 2,
                            Ios = 2,
                            Java = 4,
                            Jquery = 4,
                            Laravel = 3,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 3,
                            MySql = 0,
                            MySqlServer = 2,
                            NodeJs = 4,
                            Outras = "(Outras linguagens)",
                            Photoshop = 1,
                            Php = 0,
                            Python = 4,
                            ReactJs = 4,
                            ReactNative = 3,
                            Ruby = 3,
                            SalesForce = 2,
                            Seo = 4,
                            Swift = 2,
                            Vue = 4,
                            WordPress = 1
                        },
                        new
                        {
                            Id = 5,
                            Android = 1,
                            Angular = 0,
                            AngularJs = 3,
                            AspNetMvc = 4,
                            AspNetWebForm = 4,
                            Bootstrap = 2,
                            C = 2,
                            CSharp = 2,
                            Cake = 4,
                            CandidatoId = 5,
                            Css = 2,
                            DJango = 4,
                            ExpressNodeJs = 3,
                            Flask = 3,
                            Flutter = 1,
                            Html = 1,
                            Illustrator = 2,
                            Ionic = 2,
                            Ios = 2,
                            Java = 2,
                            Jquery = 4,
                            Laravel = 4,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 0,
                            MySql = 1,
                            MySqlServer = 0,
                            NodeJs = 2,
                            Outras = "(Outras linguagens)",
                            Photoshop = 4,
                            Php = 3,
                            Python = 3,
                            ReactJs = 3,
                            ReactNative = 4,
                            Ruby = 3,
                            SalesForce = 3,
                            Seo = 4,
                            Swift = 1,
                            Vue = 2,
                            WordPress = 3
                        },
                        new
                        {
                            Id = 6,
                            Android = 4,
                            Angular = 3,
                            AngularJs = 4,
                            AspNetMvc = 3,
                            AspNetWebForm = 3,
                            Bootstrap = 3,
                            C = 0,
                            CSharp = 0,
                            Cake = 3,
                            CandidatoId = 6,
                            Css = 1,
                            DJango = 1,
                            ExpressNodeJs = 1,
                            Flask = 2,
                            Flutter = 3,
                            Html = 3,
                            Illustrator = 0,
                            Ionic = 4,
                            Ios = 1,
                            Java = 4,
                            Jquery = 2,
                            Laravel = 0,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 0,
                            MySql = 1,
                            MySqlServer = 3,
                            NodeJs = 1,
                            Outras = "(Outras linguagens)",
                            Photoshop = 0,
                            Php = 1,
                            Python = 0,
                            ReactJs = 3,
                            ReactNative = 3,
                            Ruby = 2,
                            SalesForce = 4,
                            Seo = 2,
                            Swift = 2,
                            Vue = 0,
                            WordPress = 1
                        },
                        new
                        {
                            Id = 7,
                            Android = 4,
                            Angular = 1,
                            AngularJs = 3,
                            AspNetMvc = 4,
                            AspNetWebForm = 2,
                            Bootstrap = 3,
                            C = 4,
                            CSharp = 3,
                            Cake = 1,
                            CandidatoId = 7,
                            Css = 1,
                            DJango = 0,
                            ExpressNodeJs = 0,
                            Flask = 0,
                            Flutter = 1,
                            Html = 3,
                            Illustrator = 2,
                            Ionic = 4,
                            Ios = 2,
                            Java = 0,
                            Jquery = 4,
                            Laravel = 3,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 1,
                            MySql = 2,
                            MySqlServer = 0,
                            NodeJs = 3,
                            Outras = "(Outras linguagens)",
                            Photoshop = 3,
                            Php = 0,
                            Python = 0,
                            ReactJs = 3,
                            ReactNative = 3,
                            Ruby = 1,
                            SalesForce = 0,
                            Seo = 1,
                            Swift = 3,
                            Vue = 0,
                            WordPress = 0
                        },
                        new
                        {
                            Id = 8,
                            Android = 2,
                            Angular = 2,
                            AngularJs = 1,
                            AspNetMvc = 4,
                            AspNetWebForm = 4,
                            Bootstrap = 1,
                            C = 0,
                            CSharp = 0,
                            Cake = 4,
                            CandidatoId = 8,
                            Css = 1,
                            DJango = 3,
                            ExpressNodeJs = 0,
                            Flask = 2,
                            Flutter = 2,
                            Html = 3,
                            Illustrator = 3,
                            Ionic = 4,
                            Ios = 3,
                            Java = 0,
                            Jquery = 1,
                            Laravel = 1,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 1,
                            MySql = 1,
                            MySqlServer = 1,
                            NodeJs = 2,
                            Outras = "(Outras linguagens)",
                            Photoshop = 0,
                            Php = 0,
                            Python = 0,
                            ReactJs = 4,
                            ReactNative = 4,
                            Ruby = 2,
                            SalesForce = 0,
                            Seo = 1,
                            Swift = 3,
                            Vue = 2,
                            WordPress = 4
                        },
                        new
                        {
                            Id = 9,
                            Android = 4,
                            Angular = 1,
                            AngularJs = 1,
                            AspNetMvc = 0,
                            AspNetWebForm = 2,
                            Bootstrap = 3,
                            C = 4,
                            CSharp = 0,
                            Cake = 3,
                            CandidatoId = 9,
                            Css = 1,
                            DJango = 2,
                            ExpressNodeJs = 0,
                            Flask = 4,
                            Flutter = 4,
                            Html = 4,
                            Illustrator = 0,
                            Ionic = 2,
                            Ios = 1,
                            Java = 1,
                            Jquery = 3,
                            Laravel = 0,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 1,
                            MySql = 3,
                            MySqlServer = 1,
                            NodeJs = 1,
                            Outras = "(Outras linguagens)",
                            Photoshop = 3,
                            Php = 2,
                            Python = 0,
                            ReactJs = 4,
                            ReactNative = 4,
                            Ruby = 1,
                            SalesForce = 2,
                            Seo = 0,
                            Swift = 4,
                            Vue = 4,
                            WordPress = 2
                        },
                        new
                        {
                            Id = 10,
                            Android = 4,
                            Angular = 1,
                            AngularJs = 1,
                            AspNetMvc = 1,
                            AspNetWebForm = 0,
                            Bootstrap = 2,
                            C = 3,
                            CSharp = 1,
                            Cake = 0,
                            CandidatoId = 10,
                            Css = 4,
                            DJango = 4,
                            ExpressNodeJs = 4,
                            Flask = 4,
                            Flutter = 1,
                            Html = 3,
                            Illustrator = 0,
                            Ionic = 3,
                            Ios = 1,
                            Java = 3,
                            Jquery = 1,
                            Laravel = 2,
                            LinkCrud = "http://linkcrud.com",
                            Majento = 4,
                            MySql = 1,
                            MySqlServer = 2,
                            NodeJs = 1,
                            Outras = "(Outras linguagens)",
                            Photoshop = 2,
                            Php = 3,
                            Python = 3,
                            ReactJs = 2,
                            ReactNative = 1,
                            Ruby = 1,
                            SalesForce = 0,
                            Seo = 1,
                            Swift = 1,
                            Vue = 2,
                            WordPress = 4
                        });
                });

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Disponibilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AcimaDeOito")
                        .HasColumnType("bit");

                    b.Property<bool>("AteQuatro")
                        .HasColumnType("bit");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<bool>("FinaisDeSemana")
                        .HasColumnType("bit");

                    b.Property<bool>("QuatroAteSeis")
                        .HasColumnType("bit");

                    b.Property<bool>("SeisAteOito")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId")
                        .IsUnique();

                    b.ToTable("Disponibilidade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 1,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 2,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 2,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 3,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 3,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 4,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 4,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 5,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 5,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 6,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 6,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 7,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 7,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 8,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 8,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 9,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 9,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        },
                        new
                        {
                            Id = 10,
                            AcimaDeOito = false,
                            AteQuatro = false,
                            CandidatoId = 10,
                            FinaisDeSemana = false,
                            QuatroAteSeis = false,
                            SeisAteOito = false
                        });
                });

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Preferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<bool>("Comercial")
                        .HasColumnType("bit");

                    b.Property<bool>("Madrugada")
                        .HasColumnType("bit");

                    b.Property<bool>("Manha")
                        .HasColumnType("bit");

                    b.Property<bool>("Noite")
                        .HasColumnType("bit");

                    b.Property<bool>("Tarde")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId")
                        .IsUnique();

                    b.ToTable("Preferencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidatoId = 1,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 2,
                            CandidatoId = 2,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 3,
                            CandidatoId = 3,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 4,
                            CandidatoId = 4,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 5,
                            CandidatoId = 5,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 6,
                            CandidatoId = 6,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 7,
                            CandidatoId = 7,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 8,
                            CandidatoId = 8,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 9,
                            CandidatoId = 9,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        },
                        new
                        {
                            Id = 10,
                            CandidatoId = 10,
                            Comercial = false,
                            Madrugada = false,
                            Manha = false,
                            Noite = false,
                            Tarde = false
                        });
                });

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Conhecimento", b =>
                {
                    b.HasOne("EasyTalentos.Dominio.Entity.Candidato", "Candidato")
                        .WithOne("Conhecimento")
                        .HasForeignKey("EasyTalentos.Dominio.Entity.Conhecimento", "CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Disponibilidade", b =>
                {
                    b.HasOne("EasyTalentos.Dominio.Entity.Candidato", "Candidato")
                        .WithOne("Disponibilidade")
                        .HasForeignKey("EasyTalentos.Dominio.Entity.Disponibilidade", "CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyTalentos.Dominio.Entity.Preferencia", b =>
                {
                    b.HasOne("EasyTalentos.Dominio.Entity.Candidato", "Candidato")
                        .WithOne("Preferencia")
                        .HasForeignKey("EasyTalentos.Dominio.Entity.Preferencia", "CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
